export const antfuRules = {
  'antfu/no-top-level-await': 'error',
} as const

export const antfuImportRules = {
  'antfu/no-import-dist': 'error',
  'antfu/no-import-node-modules-by-path': 'error',
} as const

export const baseRules = {
  'accessor-pairs': [
    'error',
    {
      enforceForClassMembers: true,
      setWithoutGet: true,
    },
  ],
  'array-callback-return': 'error',
  'block-scoped-var': 'error',
  'constructor-super': 'error',
  'default-case-last': 'error',
  eqeqeq: ['error', 'smart'],
  'new-cap': [
    'error',
    {
      capIsNew: false,
      newIsCap: true,
      properties: true,
    },
  ],
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': [
    'error',
    {
      allow: ['warn', 'error'],
    },
  ],
  'no-const-assign': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': [
    'error',
    {
      allowEmptyCatch: true,
    },
  ],
  'no-empty-pattern': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implied-eval': 'error',
  'no-import-assign': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-labels': [
    'error',
    {
      allowLoop: false,
      allowSwitch: false,
    },
  ],
  'no-lone-blocks': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-multi-str': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-new-wrappers': 'error',
  'no-obj-calls': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': [
    'error',
    {
      builtinGlobals: false,
    },
  ],
  'no-regex-spaces': 'error',
  'no-restricted-globals': [
    'error',
    {
      message: 'Use `globalThis` instead.',
      name: 'global',
    },
    {
      message: 'Use `globalThis` instead.',
      name: 'self',
    },
  ],
  'no-restricted-properties': [
    'error',
    {
      message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.',
      property: '__proto__',
    },
    {
      message: 'Use `Object.defineProperty` instead.',
      property: '__defineGetter__',
    },
    {
      message: 'Use `Object.defineProperty` instead.',
      property: '__defineSetter__',
    },
    {
      message: 'Use `Object.getOwnPropertyDescriptor` instead.',
      property: '__lookupGetter__',
    },
    {
      message: 'Use `Object.getOwnPropertyDescriptor` instead.',
      property: '__lookupSetter__',
    },
  ],
  'no-self-assign': [
    'error',
    {
      props: true,
    },
  ],
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-unexpected-multiline': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': [
    'error',
    {
      defaultAssignment: false,
    },
  ],
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unused-expressions': [
    'error',
    {
      allowShortCircuit: true,
      allowTaggedTemplates: true,
      allowTernary: true,
    },
  ],
  'no-unused-vars': [
    'error',
    {
      args: 'after-used',
      argsIgnorePattern: '^_',
      caughtErrors: 'none',
      fix: {
        imports: 'safe-fix',
        variables: 'suggestion',
      },
      ignoreRestSiblings: true,
      vars: 'all',
      varsIgnorePattern: '^_',
    },
  ],
  'no-use-before-define': [
    'error',
    {
      classes: false,
      functions: false,
      variables: true,
    },
  ],
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-with': 'error',
  'object-shorthand': [
    'error',
    'always',
    {
      avoidQuotes: true,
      ignoreConstructors: false,
    },
  ],
  'prefer-arrow-callback': [
    'error',
    {
      allowNamedFunctions: false,
      allowUnboundThis: true,
    },
  ],
  'prefer-const': [
    'error',
    {
      destructuring: 'all',
      ignoreReadBeforeAssign: true,
    },
  ],
  'prefer-exponentiation-operator': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': [
    'error',
    {
      disallowRedundantWrapping: true,
    },
  ],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'symbol-description': 'error',
  'unicode-bom': ['error', 'never'],
  'use-isnan': [
    'error',
    {
      enforceForIndexOf: true,
      enforceForSwitchCase: true,
    },
  ],
  'valid-typeof': [
    'error',
    {
      requireStringLiterals: true,
    },
  ],
  'vars-on-top': 'error',
  yoda: ['error', 'never'],
} as const

export const importRules = {
  'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
  'import/first': 'error',
  'import/no-duplicates': 'error',
  'import/no-mutable-exports': 'error',
  'import/no-named-default': 'error',
} as const

export const commandRules = {
  'command/command': 'error',
} as const

export const commentsRules = {
  'eslint-comments/no-aggregating-enable': 'error',
  'eslint-comments/no-duplicate-disable': 'error',
  'eslint-comments/no-unlimited-disable': 'error',
  'eslint-comments/no-unused-enable': 'error',
} as const

export const e18eModernizationRules = {
  'e18e/prefer-array-at': 'error',
  'e18e/prefer-array-fill': 'error',
  'e18e/prefer-includes': 'error',
  'e18e/prefer-array-to-reversed': 'error',
  'e18e/prefer-array-to-sorted': 'error',
  'e18e/prefer-array-to-spliced': 'error',
  'e18e/prefer-nullish-coalescing': 'error',
  'e18e/prefer-object-has-own': 'error',
  'e18e/prefer-spread-syntax': 'error',
  'e18e/prefer-url-canparse': 'error',
} as const

export const e18eModuleReplacementRules = {
  'e18e/ban-dependencies': 'error',
} as const

export const e18ePerformanceRules = {
  'e18e/prefer-array-from-map': 'error',
  'e18e/prefer-timer-args': 'error',
  'e18e/prefer-date-now': 'error',
  'e18e/prefer-regex-test': 'error',
  'e18e/prefer-array-some': 'error',
  'e18e/prefer-static-regex': 'error',
  'e18e/prefer-string-fromcharcode': 'error',
} as const

export const jsdocRules = {
  'jsdoc/check-access': 'warn',
  'jsdoc/check-property-names': 'warn',
  'jsdoc/empty-tags': 'warn',
  'jsdoc/implements-on-classes': 'warn',
  'jsdoc/no-defaults': 'warn',
  'jsdoc/require-param-name': 'warn',
  'jsdoc/require-property': 'warn',
  'jsdoc/require-property-description': 'warn',
  'jsdoc/require-property-name': 'warn',
  'jsdoc/require-returns-description': 'warn',
} as const

export const jsxA11yRules = {
  'jsx-a11y/alt-text': 'error',
  'jsx-a11y/anchor-ambiguous-text': 'off',
  'jsx-a11y/anchor-has-content': 'error',
  'jsx-a11y/anchor-is-valid': 'error',
  'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
  'jsx-a11y/aria-props': 'error',
  'jsx-a11y/aria-proptypes': 'error',
  'jsx-a11y/aria-role': 'error',
  'jsx-a11y/aria-unsupported-elements': 'error',
  'jsx-a11y/autocomplete-valid': 'error',
  'jsx-a11y/click-events-have-key-events': 'error',
  'jsx-a11y/control-has-associated-label': 'off',
  'jsx-a11y/heading-has-content': 'error',
  'jsx-a11y/html-has-lang': 'error',
  'jsx-a11y/iframe-has-title': 'error',
  'jsx-a11y/img-redundant-alt': 'error',
  'jsx-a11y/interactive-supports-focus': [
    'error',
    {
      tabbable: ['button', 'checkbox', 'link', 'searchbox', 'spinbutton', 'switch', 'textbox'],
    },
  ],
  'jsx-a11y/label-has-associated-control': 'error',
  'jsx-a11y/media-has-caption': 'error',
  'jsx-a11y/mouse-events-have-key-events': 'error',
  'jsx-a11y/no-access-key': 'error',
  'jsx-a11y/no-autofocus': 'error',
  'jsx-a11y/no-distracting-elements': 'error',
  'jsx-a11y/no-interactive-element-to-noninteractive-role': [
    'error',
    {
      tr: ['none', 'presentation'],
      canvas: ['img'],
    },
  ],
  'jsx-a11y/no-noninteractive-element-interactions': [
    'error',
    {
      handlers: ['onClick', 'onError', 'onLoad', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
      alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
      body: ['onError', 'onLoad'],
      dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
      iframe: ['onError', 'onLoad'],
      img: ['onError', 'onLoad'],
    },
  ],
  'jsx-a11y/no-noninteractive-element-to-interactive-role': [
    'error',
    {
      ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
      ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
      li: ['menuitem', 'menuitemradio', 'menuitemcheckbox', 'option', 'row', 'tab', 'treeitem'],
      table: ['grid'],
      td: ['gridcell'],
      fieldset: ['radiogroup', 'presentation'],
    },
  ],
  'jsx-a11y/no-noninteractive-tabindex': [
    'error',
    {
      tags: [],
      roles: ['tabpanel'],
      allowExpressionValues: true,
    },
  ],
  'jsx-a11y/no-redundant-roles': 'error',
  'jsx-a11y/no-static-element-interactions': [
    'error',
    {
      allowExpressionValues: true,
      handlers: ['onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
    },
  ],
  'jsx-a11y/role-has-required-aria-props': 'error',
  'jsx-a11y/role-supports-aria-props': 'error',
  'jsx-a11y/scope': 'error',
  'jsx-a11y/tabindex-no-positive': 'error',
} as const

export const nodeRules = {
  'node/handle-callback-err': ['error', '^(err|error)$'],
  'node/no-exports-assign': 'error',
  'node/no-new-require': 'error',
  'node/no-path-concat': 'error',
} as const

export const reactRules = {
  'react/exhaustive-deps': 'warn',
  'react/no-array-index-key': 'warn',
  'react/no-clone-element': 'warn',
  'react/no-direct-mutation-state': 'error',
  'react/no-unknown-property': 'error',
  'react/rules-of-hooks': 'error',
  'react/jsx-no-comment-textnodes': 'warn',
  'react/only-export-components': [
    'error',
    {
      allowConstantExport: true,
      allowExportNames: [],
    },
  ],
  'react/style-prop-object': 'error',
} as const

export const reactXRules = {
  'react-x/error-boundaries': 'error',
  'react-x/no-access-state-in-setstate': 'error',
  'react-x/no-children-count': 'warn',
  'react-x/no-children-for-each': 'warn',
  'react-x/no-children-map': 'warn',
  'react-x/no-children-only': 'warn',
  'react-x/no-children-to-array': 'warn',
  'react-x/no-component-will-mount': 'error',
  'react-x/no-component-will-receive-props': 'error',
  'react-x/no-component-will-update': 'error',
  'react-x/no-context-provider': 'warn',
  'react-x/no-create-ref': 'error',
  'react-x/no-forward-ref': 'warn',
  'react-x/no-missing-key': 'error',
  'react-x/no-nested-component-definitions': 'error',
  'react-x/no-nested-lazy-component-declarations': 'error',
  'react-x/no-set-state-in-component-did-mount': 'warn',
  'react-x/no-set-state-in-component-did-update': 'warn',
  'react-x/no-set-state-in-component-will-update': 'warn',
  'react-x/no-unnecessary-use-prefix': 'warn',
  'react-x/no-unsafe-component-will-mount': 'warn',
  'react-x/no-unsafe-component-will-receive-props': 'warn',
  'react-x/no-unsafe-component-will-update': 'warn',
  'react-x/no-unused-class-component-members': 'warn',
  'react-x/no-use-context': 'warn',
  'react-x/purity': 'warn',
  'react-x/set-state-in-effect': 'warn',
  'react-x/set-state-in-render': 'error',
  'react-x/static-components': 'error',
  'react-x/unsupported-syntax': 'error',
  'react-x/use-memo': 'error',
  'react-x/use-state': 'warn',
  'react-x/jsx-no-children-prop': 'warn',
  'react-x/jsx-no-children-prop-with-children': 'error',
  'react-x/jsx-no-key-after-spread': 'error',
  'react-x/jsx-no-leaked-dollar': 'warn',
  'react-x/jsx-no-leaked-semicolon': 'warn',
  'react-x/jsx-no-namespace': 'error',
  'react-x/rsc-function-definition': 'error',
  'react-x/dom-no-dangerously-set-innerhtml': 'warn',
  'react-x/dom-no-dangerously-set-innerhtml-with-children': 'error',
  'react-x/dom-no-find-dom-node': 'error',
  'react-x/dom-no-flush-sync': 'error',
  'react-x/dom-no-hydrate': 'error',
  'react-x/dom-no-render': 'error',
  'react-x/dom-no-render-return-value': 'error',
  'react-x/dom-no-script-url': 'warn',
  'react-x/dom-no-unsafe-iframe-sandbox': 'warn',
  'react-x/dom-no-use-form-state': 'error',
  'react-x/dom-no-void-elements-with-children': 'error',
  'react-x/web-api-no-leaked-event-listener': 'warn',
  'react-x/web-api-no-leaked-fetch': 'warn',
  'react-x/web-api-no-leaked-intersection-observer': 'warn',
  'react-x/web-api-no-leaked-interval': 'warn',
  'react-x/web-api-no-leaked-resize-observer': 'warn',
  'react-x/web-api-no-leaked-timeout': 'warn',
  'react-x/naming-convention-context-name': 'warn',
  'react-x/naming-convention-id-name': 'warn',
  'react-x/naming-convention-ref-name': 'warn',
} as const

export const regexpRules = {
  'regexp/confusing-quantifier': 'warn',
  'regexp/control-character-escape': 'error',
  'regexp/match-any': 'error',
  'regexp/negation': 'error',
  'regexp/no-contradiction-with-assertion': 'error',
  'regexp/no-dupe-characters-character-class': 'error',
  'regexp/no-dupe-disjunctions': 'error',
  'regexp/no-empty-alternative': 'warn',
  'regexp/no-empty-capturing-group': 'error',
  'regexp/no-empty-character-class': 'error',
  'regexp/no-empty-group': 'error',
  'regexp/no-empty-lookarounds-assertion': 'error',
  'regexp/no-empty-string-literal': 'error',
  'regexp/no-escape-backspace': 'error',
  'regexp/no-extra-lookaround-assertions': 'error',
  'regexp/no-invalid-regexp': 'error',
  'regexp/no-invisible-character': 'error',
  'regexp/no-lazy-ends': 'warn',
  'regexp/no-legacy-features': 'error',
  'regexp/no-misleading-capturing-group': 'error',
  'regexp/no-misleading-unicode-character': 'error',
  'regexp/no-missing-g-flag': 'error',
  'regexp/no-non-standard-flag': 'error',
  'regexp/no-obscure-range': 'error',
  'regexp/no-optional-assertion': 'error',
  'regexp/no-potentially-useless-backreference': 'warn',
  'regexp/no-super-linear-backtracking': 'error',
  'regexp/no-trivially-nested-assertion': 'error',
  'regexp/no-trivially-nested-quantifier': 'error',
  'regexp/no-unused-capturing-group': 'error',
  'regexp/no-useless-assertions': 'error',
  'regexp/no-useless-backreference': 'error',
  'regexp/no-useless-character-class': 'error',
  'regexp/no-useless-dollar-replacements': 'error',
  'regexp/no-useless-escape': 'error',
  'regexp/no-useless-flag': 'warn',
  'regexp/no-useless-lazy': 'error',
  'regexp/no-useless-non-capturing-group': 'error',
  'regexp/no-useless-quantifier': 'error',
  'regexp/no-useless-range': 'error',
  'regexp/no-useless-set-operand': 'error',
  'regexp/no-useless-string-literal': 'error',
  'regexp/no-useless-two-nums-quantifier': 'error',
  'regexp/no-zero-quantifier': 'error',
  'regexp/optimal-lookaround-quantifier': 'warn',
  'regexp/optimal-quantifier-concatenation': 'error',
  'regexp/prefer-character-class': 'error',
  'regexp/prefer-d': 'error',
  'regexp/prefer-plus-quantifier': 'error',
  'regexp/prefer-predefined-assertion': 'error',
  'regexp/prefer-question-quantifier': 'error',
  'regexp/prefer-range': 'error',
  'regexp/prefer-set-operation': 'error',
  'regexp/prefer-star-quantifier': 'error',
  'regexp/prefer-unicode-codepoint-escapes': 'error',
  'regexp/prefer-w': 'error',
  'regexp/simplify-set-operations': 'error',
  'regexp/sort-flags': 'error',
  'regexp/strict': 'error',
  'regexp/use-ignore-case': 'error',
} as const

export const solidRules = {
  'solid/components-return-once': 'warn',
  'solid/event-handlers': [
    'error',
    {
      ignoreCase: false,
      warnOnSpread: false,
    },
  ],
  'solid/imports': 'error',
  'solid/jsx-no-duplicate-props': 'error',
  'solid/jsx-no-script-url': 'error',
  'solid/jsx-no-undef': [
    'error',
    {
      typescriptEnabled: true,
    },
  ],
  'solid/jsx-uses-vars': 'error',
  'solid/no-destructure': 'error',
  'solid/no-innerhtml': [
    'error',
    {
      allowStatic: true,
    },
  ],
  'solid/no-react-deps': 'error',
  'solid/no-react-specific-props': 'error',
  'solid/no-unknown-namespaces': 'off',
  'solid/prefer-for': 'error',
  'solid/reactivity': 'warn',
  'solid/self-closing-comp': 'error',
  'solid/style-prop': [
    'error',
    {
      styleProps: ['style', 'css'],
    },
  ],
} as const

export const testRules = {
  'vitest/consistent-test-it': [
    'error',
    {
      fn: 'it',
      withinDescribe: 'it',
    },
  ],
  'vitest/no-identical-title': 'error',
  'vitest/no-import-node-test': 'error',
  'vitest/prefer-hooks-in-order': 'error',
  'vitest/prefer-lowercase-title': 'error',
  'no-unused-expressions': 'off',
} as const

export const typescriptRules = {
  'constructor-super': 'off',
  'getter-return': 'off',
  'no-class-assign': 'off',
  'no-const-assign': 'off',
  'no-dupe-keys': 'off',
  'no-func-assign': 'off',
  'no-import-assign': 'off',
  'no-new-native-nonconstructor': 'off',
  'no-obj-calls': 'off',
  'no-redeclare': [
    'error',
    {
      builtinGlobals: false,
    },
  ],
  'no-setter-return': 'off',
  'no-this-before-super': 'off',
  'no-unreachable': 'off',
  'no-unsafe-negation': 'off',
  'no-with': 'off',
  'prefer-const': [
    'error',
    {
      destructuring: 'all',
      ignoreReadBeforeAssign: true,
    },
  ],
  'no-unused-expressions': [
    'error',
    {
      allowShortCircuit: true,
      allowTaggedTemplates: true,
      allowTernary: true,
    },
  ],
  'no-useless-constructor': 'off',
  'no-use-before-define': [
    'error',
    {
      classes: false,
      functions: false,
      variables: true,
    },
  ],
  'typescript/ban-ts-comment': [
    'error',
    {
      'ts-expect-error': 'allow-with-description',
    },
  ],
  'typescript/no-duplicate-enum-values': 'error',
  'typescript/no-dynamic-delete': 'off',
  'typescript/no-empty-object-type': [
    'error',
    {
      allowInterfaces: 'always',
    },
  ],
  'typescript/no-explicit-any': 'warn',
  'typescript/no-extra-non-null-assertion': 'error',
  'typescript/no-extraneous-class': 'off',
  'typescript/no-invalid-void-type': 'off',
  'typescript/no-misused-new': 'error',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-asserted-optional-chain': 'error',
  'typescript/no-non-null-assertion': 'off',
  'typescript/no-require-imports': 'error',
  'typescript/no-this-alias': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/no-unsafe-declaration-merging': 'error',
  'typescript/no-unsafe-function-type': 'error',
  'typescript/no-wrapper-object-types': 'error',
  'typescript/prefer-as-const': 'error',
  'typescript/prefer-literal-enum-member': 'error',
  'typescript/prefer-namespace-keyword': 'error',
  'typescript/triple-slash-reference': 'off',
  'typescript/unified-signatures': 'off',
  'typescript/consistent-type-definitions': ['error', 'interface'],
  'typescript/consistent-type-imports': [
    'error',
    {
      disallowTypeAnnotations: false,
      fixStyle: 'separate-type-imports',
      prefer: 'type-imports',
    },
  ],
  'typescript/method-signature-style': ['error', 'property'],
  'typescript/no-import-type-side-effects': 'error',
} as const

export const typescriptLibraryRules = {
  'typescript/explicit-function-return-type': [
    'error',
    {
      allowExpressions: true,
      allowHigherOrderFunctions: true,
      allowIIFEs: true,
    },
  ],
} as const

export const unicornRules = {
  'unicorn/consistent-empty-array-spread': 'error',
  'unicorn/error-message': 'error',
  'unicorn/escape-case': 'error',
  'unicorn/new-for-builtins': 'error',
  'unicorn/no-instanceof-builtins': 'error',
  'unicorn/no-new-array': 'error',
  'unicorn/no-new-buffer': 'error',
  'unicorn/number-literal-case': 'error',
  'unicorn/prefer-dom-node-text-content': 'error',
  'unicorn/prefer-includes': 'error',
  'unicorn/prefer-node-protocol': 'error',
  'unicorn/prefer-number-properties': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
  'unicorn/prefer-type-error': 'error',
  'unicorn/throw-new-error': 'error',
} as const

export const vueRules = {
  'vue/no-arrow-functions-in-watch': 'error',
  'vue/no-async-in-computed-properties': 'error',
  'vue/no-computed-properties-in-data': 'error',
  'vue/no-deprecated-data-object-declaration': 'error',
  'vue/no-deprecated-delete-set': 'error',
  'vue/no-deprecated-destroyed-lifecycle': 'error',
  'vue/no-deprecated-events-api': 'error',
  'vue/no-deprecated-model-definition': 'error',
  'vue/no-deprecated-props-default-this': 'error',
  'vue/no-deprecated-vue-config-keycodes': 'error',
  'vue/no-dupe-keys': 'off',
  'vue/no-export-in-script-setup': 'error',
  'vue/no-expose-after-await': 'error',
  'vue/no-lifecycle-after-await': 'error',
  'vue/no-reserved-component-names': 'error',
  'vue/no-reserved-keys': 'error',
  'vue/no-reserved-props': 'error',
  'vue/no-shared-component-data': 'error',
  'vue/no-side-effects-in-computed-properties': 'error',
  'vue/no-watch-after-await': 'error',
  'vue/prefer-import-from-vue': 'error',
  'vue/require-prop-type-constructor': 'error',
  'vue/require-render-return': 'error',
  'vue/require-slots-as-functions': 'error',
  'vue/return-in-computed-property': 'error',
  'vue/return-in-emits-validator': 'error',
  'vue/valid-define-emits': 'error',
  'vue/valid-define-options': 'error',
  'vue/valid-define-props': 'error',
  'vue/valid-next-tick': 'error',
  'vue/component-definition-name-casing': 'warn',
  'vue/prop-name-casing': ['error', 'camelCase'],
  'vue/require-default-prop': 'off',
  'vue/require-prop-types': 'off',
  'vue/no-multiple-slot-args': 'warn',
  'vue/no-required-prop-with-default': 'warn',
} as const
